name: Generate

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install OpenSCAD
      run: sudo apt-get install -y openscad

    - name: Generate STL and PNG
      run: |
        mkdir -p output
        mkdir -p output/example
        Xvfb :99 & export DISPLAY=:99
        #openscad -o output/example/model.stl examples.2.scad
        openscad -o output/example/model.png --imgsize=1024,768 --projection=o --autocenter --viewall examples.2.scad

    - name: Upload STL and PNG
      uses: actions/upload-artifact@v4
      with:
        name: OpenSCAD Outputs
        path: output/
