name: Generate

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix-env -iA nixpkgs.openscad-unstable
    
    - name: Generate STL and PNG
      run: |
        mkdir -p output
        mkdir -p output/example
        Xvfb :99 & export DISPLAY=:99
        #openscad --backend=manifold -o output/example/model.stl examples.2.scad
        openscad --backend=manifold --render -o output/example/model_top.png --imgsize=2048,2048 --projection=o --camera=0,0,100,0,0,0,1 --autocenter --viewall examples.2.scad
        openscad --backend=manifold --render -o output/example/model_iso.png --imgsize=2048,2048 --projection=o --camera=50,50,50,55,0,25,1 --autocenter --viewall examples.2.scad

    - name: Upload STL and PNG
      uses: actions/upload-artifact@v4
      with:
        name: Outputs
        path: output/*
